# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" , "dev-weixuan-1", "weixuanseow-patch-1"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run unit tests
      run: |
        python $GITHUB_WORKSPACE/backend/unit_tests.py
    - name: Start Flask application
      run: |
          cd $GITHUB_WORKSPACE/backend
          python app.py &
          sleep 3  
    - name: Run integration tests
      run: |
          cd $GITHUB_WORKSPACE/backend
          python integration_tests.py
